### ISSUE TITLE
Request for guide for AWS deployment

### ISSUE THREAD

**Issue by Pete-Fowler** [learn-co-curriculum/phase-4-deploying-rails-api-to-render#1]
### Canvas Link

https://learning.flatironschool.com/courses/5223/pages/deploying-a-rails-api-to-render?module_item_id=494203

### Concern

Thanks for the walkthrough on Render. Since AWS seems to be the thing most or all employers are looking for and it does not suffer from the 30+ second load times of a free Render account, I'd love to see a Flatiron guide on how to deploy on Elastic Beanstalk.

**Comment by lizbur10** [comment]
Hi @Pete-Fowler ! Thanks for the suggestion. The decision process for deciding which solution to include in the curriculum was complicated and it was difficult to find anything that met all the criteria. We will keep your suggestion in mind as a possible supplemental option in future updates to this material. 

In the meantime, you are, of course, free to use whichever deployment solution works for you.

Thanks for contributing to the Flatiron School curriculum 💙
